feat: 프로필 페이지 기능추가
Breaking-Dope/breaking-frontend pull request #112
Opened 2022-07-19 02:29 UTC by Yoon-Hae-Min

## 관련 이슈

close #74 

## 예상 리뷰 시간
40-min (파이팅!!!)

## 추가 또는 변경사항
프로필페이지에 기능들을 전부(?)는 아니지만 거의다 추가하였습니다
생각보다 api가 많아서 정리하는데 시간이 많이 들어간것 같습니다

추가된 부분

1. 팔로우 팔로워 버튼을 클릭하면 api를 던져서 데이터를 받아옵니다
2. profile/0은 내 페이지이고 profile/1은 남의 페이지 입니다 페이지에 따라서 볼 수 있는 tabs와 팔로우 버튼이 바뀝니다.
3. 팔로우 버튼이 눌리면 api를 실행시키고 자동으로 유저의 데이터를 refetch시킵니다
4. tabs에 따라 filter는 각각 독립적으로 작동합니다 filter도 누를시에 api를 실행합니다.

한계점

1. msw에서 filter내용을 가져오려면 search라는 params를 사용해야 하는데 아직 이거는 추가를 안했습니다 공부좀 더 하고 추가하면 filter에 따라서 받아오는 게시글도 다르게 할수 있습니다 물론 그전에 mocking 파일분리부터 먼저 해야할것 같습니다
2. 지금페이지가 내페이지인지 체크하는 function을 하나 만들어야하는데 아직 로그인정보의 로직이 없어 임의로 ture false로 구별하였습니다 utils로 function을 빼서 체크하는 함수를 하나 만들고 유저페이지와 게시글 페이지에 써먹는것이 좋아보입니다 이건 로그인후에 데이터처리를 하고 만들 예정입니다.
3. 팔로우 리스트에서 삭제버튼을 눌렀을때 언팔로우 api를 실행해야 하는데 아직 미구현 입니다.

## 스크린샷

클릭해볼게 많기때문에 한번 로컬에서 돌려보시는것을 추천합니다.

## 기타

최대한 유지보수가 좋게 짜봤습니다 파일분리 의존성 응집도 생각하면서 짜니까 어렵군요... 그래도 최대한 깨끗하게 짠거 같아 마음은 놓입니다.

2022-07-19 05:47 UTC, kangju2000 requested changes
profile/0과 profile/1의 UserInformation의 위치가 살짝 다릅니다!

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/hooks/queries/useProfile.js
> +const { useQuery } = require('react-query');
require에서 import로!

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/hooks/queries/useFollowList.js
> +const useFollow = (target, userId) => {
파일명과 동일한 함수명으로 작성해주세욥

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/mocks/handlers.js
> +          profileImgURL: '',
'두피' 돌림이었군요? 😎

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/hooks/queries/useProfilePost.js
> +const { useQuery } = require('react-query');
require->import

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/hooks/queries/useProfilePost.js
> +    { enabled: enabled }
`refetchOnWindowFocus: false` 추가하면 윈도우가 포커스되어도 refetch를 안하게됩니다! QueryClient의 Default Option으로 저 옵션을 넣어주면 따로 설정하지 않아도 됩니다. 
```javascript
const queryClient = new QueryClient({
    defaultOptions: {
      queries: { refetchOnWindowFocus: false },
      mutations: {},
    },
```

그리고 enabled라는 변수를 만들지 않고 그냥 enabled: isMyPage로 하면 되지 않을까요?

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/units/ProfileFollowButton.js
> +        <Button>팔로우</Button>
팔로우 버튼이 좀 큰거 같아요..

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/api/profile.js
> +import api from './api';
절대 경로!

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/units/ProfileFollowButton.stlye.js
> +
파일 이름 오타있어용

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/units/ProfileTabPanel.js
> +    <>
Fragment `<></>` 빼도 될거같아욥

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/Profile.styles.js
>    font-size: 36px;
32px로 하면 좋을거 같아요! 실제로 보니 좀 커보이네요

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/hooks/queries/useFollowList.js
> +  const { data, isLoading } = useQuery([target, userId], targetApi, {});
처음 프로필 페이지 들어갔을 때 팔로잉 데이터만 불러오고 팔로워 데이터는 안불러오네요.
유저가 팔로잉 또는 팔로워 버튼을 누를때에만 실행하도록 enabled: false 설정하면 좋지 않을까요?

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/Profile.js
> +            isPermission={true}
isPermission={isMyPage}

2022-07-19 05:47 UTC, kangju2000 commented on breaking-front/src/pages/Profile/Profile.js
> +            key={item.key}
콘솔에 key값이 없어서 오류가 나오는데 확인할 수 있을까요?
![image](https://user-images.githubusercontent.com/23312485/179674554-518bf89d-4c3a-40cc-8838-20d27647e07d.png)

2022-07-19 05:58 UTC, Yoon-Hae-Min commented on breaking-front/src/hooks/queries/useFollowList.js
> +const useFollow = (target, userId) => {
이름 수정중에 다른파일은 고쳤는데 본파일은 안고쳤군요 ㅋㅋㅋㅋ

2022-07-19 05:58 UTC, Yoon-Hae-Min commented on breaking-front/src/hooks/queries/useProfilePost.js
> +const { useQuery } = require('react-query');
믿었던 자동완성의 배신....

2022-07-19 06:05 UTC, Yoon-Hae-Min commented on breaking-front/src/hooks/queries/useProfilePost.js
> +    { enabled: enabled }
전자는 반영하겠습니다. focus시에 refetch이라니.... 항상 개발하면서 control+s를 계속 눌러서 그것땜에 refetch되는 줄 알았는데 이건 몰랐네요

enabled: isMyPage로 가면 written 게시글도 내 페이지면 요청이 가질 않습니다

2022-07-19 06:07 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Profile/units/ProfileTabPanel.js
> +    <>
빈값을 넘겨줘야해서 빈 fragment로 넘겨주었습니다. 뭔가 jsx 리턴시에는 다 tag로 해야할것 같아서? 썼읍니다.

2022-07-19 06:08 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Profile/Profile.js
> +            isPermission={true}
아앗.. 수정안했다...

2022-07-19 06:12 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Profile/Profile.js
> +            key={item.key}
이거 처음 랜더링할때 순서 차이 때문에 생기는것 같아요 딱 처음시 에만 저에러가 뜨더라고요

2022-07-19 06:12 UTC, Yoon-Hae-Min commented on breaking-front/src/hooks/queries/useFollowList.js
> +  const { data, isLoading } = useQuery([target, userId], targetApi, {});
좋습니다!!!

2022-07-20 03:14 UTC, kangju2000 approved these changes
커밋 44개!! 수고하셨습니다

2022-07-20 03:14 UTC, merged