feat: 제보글 상세 페이지 기능 추가
Breaking-Dope/breaking-frontend pull request #140
Opened 2022-07-28 14:19 UTC by kangju2000

## 관련 이슈

close #136

## 예상 리뷰 시간
25-min

## 추가 또는 변경사항

제보글 상세 페이지에 들어가는 기능들을 추가했습니다.
api mocking 또한 했기 때문에 console에서 확인할 수 있습니다.

- 제보 좋아요, 북마크 기능 구현

- 댓글 좋아요, 수정 및 삭제 기능, 작성 시 '#'을 붙히게 되면 그 뒤에 나오는 단어를 해시태그로 인식하여 hashtagList로 보내도록 구현하고 해시태그는 파란색으로 하이라이트 되어 보여지도록 구현

- 댓글 무한 스크롤링 구현. 로딩 시 스피너가 돌아가도록 구현

- 대댓글은 무한스크롤링 대신 더보기 버튼으로 동작하도록 설정

- CommentForm에 들어가는 input을 textarea로 변경 후, 엔터 시 submit 되지 않고 textarea가 맞춰 커지도록 구현

- Post의 content와 Comment의 content에 '\n'이 있으면 `<br />` 처리하여 띄어쓰기 구현

- 구매자 목록 클릭 시 Modal이 뜨도록 구현

## 스크린샷

![Uploading Animation (4).gif…]()

## 기타

list를 가져오는 api들은 data가 배열 형태이기 때문에 `{ content: [{...},{...} }` 이런식으로 받아와집니다. 이전에 작성했던 메인 피드에서 이것을 고려하지 않고 작성했었기 때문에 수정할 예정입니다.
그리고 현재 api sheet에도 잘못 되어있는 부분이 많기에 수정 요청 또한 하겠습니다.

2022-07-29 03:33 UTC, Yoon-Hae-Min requested changes
![1](https://user-images.githubusercontent.com/49224104/181676889-7e97019f-af89-4bd4-b3c5-3c2fc342be6c.gif)


첫 액션을 취할시에 본문이 깜빡거리던데 방안을 찾아보려고 코드를 봤지만 찾지 못했습니다 ㅠㅠ 제컴퓨터 문제일까요?

![2](https://user-images.githubusercontent.com/49224104/181676897-0010c7f6-39bd-4e81-8c41-274110c74810.gif)
좋아요 버튼을 누를시에 옆에 댓글아이콘이 1px정도 밀리는거 같습니다.

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/constants/path.js
> +  POST_COMMENT_DATA: (postId, cursorId, size = '10') =>
변수명 cursor로 통일하는거 어떤가요?

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
> +        <Style.BackIconContainer onClick={() => navigate(PAGE_PATH.HOME)}>
프로필 페이지에서 들어온거 일수도 있으니 navigate(-1)로 페이지 뒤로가기 하는건 어떤가요?

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
> +            {purchaseType === '구매자 목록' && (
state로 관리하지말고 `PostData?.data.isSold ?` 처럼 data내에서 직접 받아와서 처리하는건 어떤가요?

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
> +              <Style.Hashtag key={'hashtag-' + index}>#{hashtag}</Style.Hashtag>
해시태그들 cursor pointer로 해주세용

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
> +              <Style.Loading type="spin" color="#014d91" width="40px" />
color 색상 useTheme hook사용해 주세요

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.styles.js
> +export const Loading = styled(ReactLoading)`
ReactLoading자체가 컴포넌트라 이런것도 가능하네요

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/units/Comment.js
> +            <Style.Loading type="spin" color="#014d91" width="40px" />
요기도 useTheme hook!!!

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/units/CommentForm.js
> +    if (textareaRef === null || textareaRef.current === null) return;
이줄 없이도 작동합니다 textareaRef가 에러가 날거면 useEffect있는 부분에서 먼저 일어날거라 필요가 없습니다

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/units/CommentForm.js
> +  useEffect(() => {
없어도 동작하던데 넣은 이유가 있나요?

2022-07-29 03:33 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/units/CommentForm.js
> +    textareaRef.current.style.height = textareaRef.current.scrollHeight + 'px';
스크롤까지 생각하는 디테일 크으~~

2022-07-29 04:24 UTC, kangju2000 commented on breaking-front/src/pages/Post/units/CommentForm.js
> +  useEffect(() => {
댓글 수정 시 글자가 잘려보이기 때문에 사용했습니다

2022-07-29 04:56 UTC, kangju2000 commented on breaking-front/src/pages/Post/Post.js
> +            {purchaseType === '구매자 목록' && (
삼항 연산자를 중첩해서 써야하는 상황이 나오기 때문에 state로 관리했습니다. 그리고 판매가 중지되는 필드가 추가되면 더 복잡해질 것을 감안해서 이렇게 작성했습니다.

2022-07-31 12:03 UTC, Yoon-Hae-Min approved these changes
직접 연결하는것만 남았군요 고생하셨어요

2022-08-01 01:04 UTC, merged