feat: post write 페이지 form데이터 추가
Breaking-Dope/breaking-frontend pull request #154
Opened 2022-08-05 08:27 UTC by Yoon-Hae-Min

## 관련 이슈

close #152 

## 예상 리뷰 시간
15-min

## 추가 또는 변경사항

1. 제보방식이 무료면 제보가격 입력창을 숨겼습니다
2. 위치,제목,본문 내용을 입력하지 않을시 에러 창이 띄워집니다.
3. 본문의 해시태그를 추출해서 백엔드에 데이터로 보내집니다.
4. 발생시간 input창이 2개에서 하나로 합쳐졌습니다 그에 따라서 로직이 조금 변경되었습니다.
5. 제보 가격의 input창에서 엔터 클릭시 submit되는 현상을 해결했습니다.
6. 제보 가격에서 문자 입력시에 NaN이 출력되는걸 해결했습니다.
7. 위치 modal에서 keyword로 검색할시에 from을 사용했는데 form안에 form태그를 사용할수 없어서 로직을 변경하였습니다.

## 스크린샷

변경사항 없음

## 기타

현재 썸네일은 첫번째 사진/동영상 으로 되어있는데 이걸 선택할수 있게 세부기능들 추가할때 한번 시도해보는것도 좋아 보입니다.

2022-08-07 13:07 UTC, kangju2000 requested changes
파일 추가할 때 accept 속성으로 이미지 파일과 비디오 파일만 가능하도록 막을 수 있습니다.
https://blog.munilive.com/posts/input-file-type-accept-attribute.html

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +    // 해시태그 추출
해시태그 리스트는 '#'을 뺀 상태로 백엔드로 보내야합니다. 그리고 현재 쓰인 정규식은 '\n'도 찾고 있기 때문에 이렇게 수정하는걸 추천드립니다.
```suggestion
    const hashtagList = postWriteData.content
      .match(/#[^\s#]+/g)
      ?.map((hashtag) => hashtag.replace('#', ''));
```

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +    formData.append('mediaList', mediaList);
https://stackoverflow.com/questions/12989442/uploading-multiple-files-using-formdata
```suggestion
     for (let i = 0; i < mediaList.length; i++) {
      formData.append('mediaList', mediaList[i]);
    }
```

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +        hashtagList: hashtagList.length === 0 ? 'null' : hashtagList,
위의 방식으로 수정한다면 이부분도 수정해야됩니다. hashtag가 없을 때 hashtagList는 undefined가 되기 때문입니다

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +        eventTime: dayjs(postWriteData.eventTime).format('YYYY-MM-DD HH:ss:ss'),
분 단위를 정확하게 보내지 않는 문제가 있습니다!
```suggestion
        eventTime: dayjs(postWriteData.eventTime).format('YYYY-MM-DD HH:mm:ss'),
```

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +    }
숫자 외의 문자를 입력하면 price가 0으로 초기화됩니다. 
입력을 막는게 더 좋아보입니다!
```suggestion
    if (Number.isNaN(price)) return;
```

2022-08-07 13:07 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/units/PostWriteUploadMediaForm.js
>      window.URL.revokeObjectURL(filesThumbnail[target]);
```suggestion
    URL.revokeObjectURL(filesThumbnail[target]);
```

2022-08-08 01:52 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/PostWrite/PostWrite.js
> +    formData.append('mediaList', mediaList);
array로 넘아가야 되는거였군요... 저는 잘넘어간건줄 알았습니다

2022-08-08 02:28 UTC, kangju2000 approved these changes
업로드 잘되네요! 수고하셨습니다

2022-08-08 02:48 UTC, merged