feat: postEdit 페이지를 생성한다.
Breaking-Dope/breaking-frontend pull request #176
Opened 2022-08-13 04:52 UTC by Yoon-Hae-Min

## 관련 이슈

close #171 

## 예상 리뷰 시간
15-min

## 추가 또는 변경사항

가장 큰것으로는 파일 분리가 되었다는 점입니다. 수정 기능으로 코드추가는 별로 없지만 구조 재조정으로 수정파일이 많아졌네요

1. postWrite페이지에서 공통인 부분을 추출하여 components로 이동
2. PostWriteCommonForm 에서 각 값의 value 추가하여 페이지단에서 데이터를 관리하도록 수정
3. PostEdit 페이지를 생성
4. submitButton을 수정 작성 페이지에 각각 적용
5. edit페이지 api mocking 추가
6. 해시태그 추출하는 util추가

## 스크린샷

![image](https://user-images.githubusercontent.com/49224104/184468651-1a4e3dc8-2f99-4983-bdf4-0b118ddcd385.png)

## 기타

- 일단 수정후 redirect 부분을 뒤로가기로 설정했습니다 수정페이지가 작동을 할때는 세부 게시글 페이지에서 수정페이지로 밖에 접근하지 못하니 뒤로가기로 작성해도 문제 없을것 같습니다.

- 구조적인것은 제가 봤을때는 이 정도가 좋을것 같습니다 최대한 컴포넌트나 함수 하나에 한가지 일만 할 수 있도록 분리하였습니다.

2022-08-13 14:30 UTC, kangju2000 requested changes

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/constants/path.js
> +  POST_EDIT: '/post/edit',
```suggestion
  POST_EDIT: (postId) => `/post/${postId}/edit`,
```
이렇게 하는 건 어떨까요? 만약 유저가 작성하지 않은 페이지면 에러페이지를 띄우거나 alert를 띄워 못들어가게 하면 좋을 것 같습니다.

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/mocks/postEditHandlers.js
> +  rest.put(API_PATH.POST_EDIT('*'), (req, res, ctx) => {
```suggestion
  rest.put(API_PATH.POST_EDIT(':postId'), (req, res, ctx) => {
```
* 표시는 querystring일 때만 쓰면 좋겠습니다!

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/pages/PostEdit/PostEdit.styles.js
> +  font-weight: bold;
globalStyle에서 300, 500, 700으로 굵기를 설정했기 때문에 `font-weight: 700;` 으로 바꾸는게 좋아보입니다!

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/pages/PostEdit/hooks/usePostEditMutation.js
> +      navigate(-1);
수정한 게시글 페이지로 이동하면 되지 않을까요?

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +        ></Style.DatePicker>
닫는 태그 지워주시기 바랍니다!

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +        ></Style.PostPriceInput>
닫는태그 지워주세요~

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +          }}
함수로 따로 빼는게 좋을 것 같습니다

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/hooks/usePostWriteMutation.js
> +      navigate(PAGE_PATH.HOME);
작성 완료 시 작성된 게시글 페이지로 넘어가는게 좋을 거 같은데 백엔드쪽에서 postId 값을 받아오게하는 건 어떨까요?

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/utils/extractHashTag.js
> +export default extractHashtag;
파일 이름을 함수명과 통일해주시기 바랍니다!

2022-08-13 14:30 UTC, kangju2000 commented on breaking-front/src/pages/PostWrite/PostWrite.js
>    const postWriteSubmit = (event) => {
이곳에도 extractHashtag 메소드를 사용해야 할 것 같습니다!

2022-08-14 11:15 UTC, Yoon-Hae-Min commented on breaking-front/src/constants/path.js
> +  POST_EDIT: '/post/edit',
1. 프로필 수정페이지와 같게 post/edit으로 통일했습니다.
2. post_edit에 postId가 url에 필요한 이유를 찾지 못했습니다.

2022-08-14 11:20 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/PostEdit/PostEdit.styles.js
> +  font-weight: bold;
css상에서 bold===700 입니다

2022-08-14 11:29 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/PostWrite/hooks/usePostWriteMutation.js
> +      navigate(PAGE_PATH.HOME);
보통 글을 작성하고 나면 게시글 페이지로 넘어가는게 아닌 게시글의목록으로 넘어가는게 대부분이라 게시글의 목록인 홈 화면이 더 좋을것 같습니다.

2022-08-14 11:46 UTC, Yoon-Hae-Min commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +          }}
함수로 따로 빼도 함수를 사용하는 곳이 이 곳만 있고 onKeyDown이라는 이벤트 자체도 하나 뿐 이어서 이렇게 적용하였습니다.

2022-08-17 10:04 UTC, kangju2000 commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +  };
maxLength를 이미 15로 설정해서 15글자 이상 작성할 수 없을텐데 이런 처리를 한 이유가 있나요?  16글자 이상을 복사해서 입력한다해도 15글자 이상 들어가지 않습니다.

2022-08-17 10:04 UTC, kangju2000 commented on breaking-front/src/pages/PostEdit/PostEdit.js
> +          ※ 이미지 동영상 파일은 수정할수 없습니다 ※
```suggestion
          ※ 이미지 동영상 파일은 수정할 수 없습니다 ※
```

2022-08-17 14:19 UTC, Yoon-Hae-Min commented on breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
> +  };
input type이 number일 경우에는 maxLength가 적용되지 않습니다. 이걸 적용을 시키려면 따로 함수를 만들어야 합니다.
https://cofs.tistory.com/215

2022-08-17 22:08 UTC, kangju2000 approved these changes

2022-08-18 01:39 UTC, merged