refactor: 게시글 세부 조회 페이지 리팩토링
Breaking-Dope/breaking-frontend pull request #204
Opened 2022-08-22 05:41 UTC by kangju2000

## 관련 이슈

#188

## 예상 리뷰 시간
8-min

## 추가 또는 변경사항

게시글 세부 조회 페이지를 리팩토링했습니다. 구매자 리스트 및 좋아요한 사람 리스트는 아직 구현하지 않았습니다.

- 폴더 구조 변경(hooks, components)
- 활성화 / 비활성화 기능 추가
- 제보 구매 시 버튼 변경 및 balance 업데이트

2022-08-22 08:36 UTC, Yoon-Hae-Min requested changes

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
>                    <Button color="primary">{purchaseType}</Button>
260번째줄 utils로 따로 만들어 주세요

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
>                      <Toggle width="100px">
토글도 따로 컴포넌트로 빼주세요

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
182번째줄 tag컴포넌트로 치환해 주세요

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/components/Comment/Comment.js
118번째 줄 utils로 빼주세요

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/components/Comment/Comment.js
>      navigate(PAGE_PATH.PROFILE(comment.user.userId));
193번째줄 reply로 컴포넌트를 따로 빼는건 어떤가요?

2022-08-22 08:36 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/components/CommentForm/CommentForm.js
>    const handleChange = (event) => {
type을 이용해서 mutation를 쏘는것보다는 props로 해당되는 mutation을 받아오는건 어떤가요? form은 from만 관리하고 submit이나 cancel 버튼은 상위에서 관리하도록 하는거죠

2022-08-23 13:32 UTC, Yoon-Hae-Min commented on breaking-front/src/components/ContentSlice/ContentSlice.js
> +export default function ContentSlice({ content }) {
ContentHashtagSlice는 어떤가요?

2022-08-23 13:32 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/components/CommentContainer/CommentContainer.js
> +
공백 제거해주세요

2022-08-23 13:32 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/Post/Post.js
> +        <CommentContainer postId={postId} />
CommentList는 어떤가요? container라는 이름은 css에서 사용하여서 의미를 전달하기 조금 부족한것 같아요

2022-08-23 16:23 UTC, kangju2000 commented on breaking-front/src/components/ContentSlice/ContentSlice.js
> +export default function ContentSlice({ content }) {
ContentHashtag로 바꾸겠습니다!

2022-08-24 01:36 UTC, Yoon-Hae-Min approved these changes
이상적인 코드가 되어가고있어요😆

2022-08-24 01:57 UTC, merged