feat: 브레이킹 미션 페이지 UI 구현
Breaking-Dope/breaking-frontend pull request #267
Opened 2022-09-18 13:49 UTC by kangju2000

## 관련 이슈

close #263

## 예상 리뷰 시간
6-min

## 추가 또는 변경사항

브레이킹 미션 페이지 UI를 더미데이터를 이용해 구현했습니다.

UI에 대해 수정할 부분이 있다면 코멘트 남겨주시기 바랍니다!

## 스크린샷

![image](https://user-images.githubusercontent.com/23312485/190908126-734c5edc-8380-49d8-9b93-ae2c9f5e2f75.png)

2022-09-23 01:30 UTC, Yoon-Hae-Min requested changes
ShareModal의 path부분을 PAGE_PATH를 이용해서  바꾸셨던데 기존보다 알맞는 선택인것 같습니다

2022-09-23 01:30 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/BreakingMission/MissionPost/components/MissionPostFeed/MissionPostFeed.js
> +import useMissionPostFeed from '../../hooks/queries/useMissionPostFeed';
절대경로 수정바랍니다

2022-09-23 01:30 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/BreakingMission/MissionPost/components/SubmitButton/SubmitButton.js
> +const SubmitButton = () => {
따로 분리하신 이유가 있을까요?

2022-09-23 01:30 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/BreakingMission/MissionPost/MissionPost.js
> +            <Style.ContentTitle>{missionData?.data.title}</Style.ContentTitle>
jsx부분을 Context children부분의 prefix를 content 대신에 context로 바꾸는건 어떤가요? 해당 부분은 context의 title과 body(location, viewCount createdDate)부분이라고 생각하고있습니다

2022-09-23 01:30 UTC, Yoon-Hae-Min commented on breaking-front/src/pages/BreakingMission/MissionPost/MissionPost.js
> +            <Style.ContentToggle
다른 페이지와 마찬가지로 toggle 부분도 분리하면 어떤가요? 아직은 들어가는 내용이 적지만 추후에 충분히 추가될 수 있어보입니다.

2022-09-23 06:41 UTC, kangju2000 commented on breaking-front/src/pages/BreakingMission/MissionPost/components/SubmitButton/SubmitButton.js
> +const SubmitButton = () => {
제출하기가 활성화 됐을 때와 비활성화 됐을 때의 로직이 있기 때문에 분리해두었습니다.

2022-09-25 13:37 UTC, Yoon-Hae-Min approved these changes

2022-09-26 02:50 UTC, JinuCheon commented
Good!

2022-09-26 13:01 UTC, merged