feat: 로그인 페이지 UI 생성
Breaking-Dope/breaking-frontend pull request #48
Opened 2022-07-04 06:26 UTC by Yoon-Hae-Min

## 관련 이슈

close #10 

## 예상 리뷰 시간
7-min

## 추가 또는 변경사항
피그마에 있는 UI를 구현하였습니다 피그마 툴에 있는 값들이 정확하게 몇 px인지 몰라 임의로 설정했는데 다르다거나 티가 좀 난다 싶으면 피드백 바라겠습니다. 아직 로그인은 백엔드와의 연결이 안되어 있습니다.

## 스크린샷
![image](https://user-images.githubusercontent.com/49224104/177093262-95ed442f-990f-47ca-ad6f-c2150a26057d.png)

## 기타

수동 UI 테스트
1. 현제 branch feat/10-create-login-page-UI를 clone한다
2. clone한 폴더경로 에서 터미널로 breaking-frontend로 들어간다 
![image](https://user-images.githubusercontent.com/49224104/177093404-fbccbe09-bbfd-43eb-8ca0-f6c625a64978.png)
이렇게 설정 되야함
3. npm run start를 터미널에 입력한다
4. react-app이 실행이 되는데 주소창에 locallhost:3000/login으로 변경한다
![image](https://user-images.githubusercontent.com/49224104/177093606-97acf6f1-835b-4790-95d3-9589ad865056.png)
다음과 같이 나오면됨

2022-07-04 08:43 UTC, JinuCheon approved these changes
우하하! 고생하셨어요.

디자이너 없이 기대보다 훨 좋은 결과가 나와서,
이 PM은 너무 행복합니다.

2022-07-04 09:23 UTC, SeungGun commented
피그마에 디자인하신대로 완벽하게 구현하신거 같습니다. 
그런데 이건 제 생각이긴한데, 각 객체들이 모두 화면 중앙에 몰려 있어서 남은 여백들이 많은 것이 조금 아쉬운거 같아요. 
그래서 제 의견으로는 각 객체들의 크기를 조금만 더 키우고, 각 객체간의  거리를 조금만 더 띄우면 좋을 것 같다는 생각이 듭니다!

2022-07-04 09:24 UTC, SeungGun requested changes
피그마에 디자인하신대로 완벽하게 구현하신거 같습니다. 
그런데 이건 제 생각이긴한데, 각 객체들이 모두 화면 중앙에 몰려 있어서 남은 여백들이 많은 것이 조금 아쉬운거 같아요. 
그래서 제 의견으로는 각 객체들의 크기를 조금만 더 키우고, 각 객체간의  거리를 조금만 더 띄우면 좋을 것 같다는 생각이 듭니다!

2022-07-04 10:18 UTC, Taehyuny commented
기존 도안대로 매우 잘 디자인하신 것 같습니다! 한 가지 제 의견으로는 저도 승건님과 마찬가지로, 브레이킹 로고와 옆의 버튼들이 가운데에 몰려있다는 느낌이 살짝 듭니다! 그래서 여백을 주거나, 이미지 크기를 키워서 여백을 없애면 보다 좋을 것 같습니다.

2022-07-04 12:15 UTC, kangju2000 reviewed
코딩 컨벤션 조금만 더 신경써주시면 완벽~!!

2022-07-04 12:15 UTC, kangju2000 commented on breaking-front/src/pages/SocialLogin/SocialLogin.js
> +        <SocialLoginButton social="kakao" onClick={KakaoLoginOnClick} />
KakaoLoginOnClick이 어디있을까요? 그리고 KakaoLoginClick으로 하는게 GoogleLoginClick과 통일성이 있어보입니다!

2022-07-04 12:15 UTC, kangju2000 commented on breaking-front/src/pages/SocialLogin/SocialLogin.js
> +      <Style.RightContent>
RightContent라는 변수명보다 더 명확한 변수명으로 바꾸는게 좋을 것 같아요 !

2022-07-04 12:15 UTC, kangju2000 commented on breaking-front/src/pages/SocialLogin/SocialLogin.style.js
> +  padding: 15px;
코딩 컨벤션 맞춰주세용 ~:)

2022-07-05 01:38 UTC, kangju2000 approved these changes
첫 페이지 생성 수고하셨습니다 👍

2022-07-05 01:42 UTC, merged